# Generated by Django 3.1.6 on 2021-05-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinment',
            old_name='date1',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appoinment',
            old_name='time1',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='doctor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='patient',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
