# Generated by Django 3.1.6 on 2021-05-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_auto_20210518_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='doctor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='patient',
            field=models.CharField(max_length=50),
        ),
    ]
