# Generated by Django 3.1.6 on 2021-05-18 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_auto_20210518_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.patient'),
        ),
    ]
