# Generated by Django 3.1.6 on 2021-05-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0005_auto_20210518_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='doctorid',
            field=models.IntegerField(null=True),
        ),
    ]
