# Generated by Django 3.1.6 on 2021-05-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0007_auto_20210518_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
